/**
 * Where the Command Dock can sit and how a drag moves it, with no React and no
 * DOM.
 *
 * The edges, the three stops along each, the twelve slots they make, the
 * insets and styles that place a slot, which way a menu opens from it, how a
 * slot is named, and when a press on the grip becomes a drag. `CommandDock.tsx`
 * measures the DOM and hands the rectangles here; everything decided about them
 * is answered by this module and held by node-environment tests
 * (`packages/app/test/dock-geometry.test.ts`, `dock-slots.test.ts`,
 * `dock-orientation.test.ts` and `dock-placement.test.ts`).
 */

/* ------------------------------------------------------------------ slots */

/**
 * Which edge the Dock is against.
 *
 * The edge makes three decisions at once and they are not independent: the
 * orientation the Dock draws in, which way its menus open, and how much
 * clearance it needs from the browser's own furniture.
 *
 * **The union is derived from the tuple, not checked against it.** Written the
 * other way — `['top', …] as const satisfies readonly DockEdge[]` — the check
 * proves every element *is* an edge and says nothing about an edge that is
 * missing. Add a fifth and the menu quietly offers twelve slots for fifteen,
 * with nothing red anywhere. Deriving makes the tuple the definition, so the
 * menu and every `Record<DockEdge, …>` in the surface stay total by
 * construction.
 */
export const DOCK_EDGES = ['top', 'right', 'bottom', 'left'] as const;
export type DockEdge = (typeof DOCK_EDGES)[number];

/**
 * Where along its edge the Dock sits: the two ends, and the middle.
 *
 * Quantised rather than free. A dock is furniture, and furniture that can be
 * left at 37% of an edge is furniture the next person has to look for; three
 * stops per edge is enough to get it out of the way of whatever the canvas is
 * doing, and each stop is somewhere a reader can be told to look.
 *
 * **The corners come out of this for free, and are reachable twice.** `end` of
 * the top edge and `start` of the right edge are the same corner, approached
 * from two directions — and which one you dragged from decides whether the Dock
 * is horizontal or vertical there. That is the choice, not an ambiguity: the
 * eight targets a pointer sees are four corners and four edge-middles, and a
 * corner offers two of them. The menu offers twelve rather than eight for the
 * same reason — see `DOCK_SLOTS`.
 */
export const DOCK_ALONGS = ['start', 'center', 'end'] as const;
export type DockAlong = (typeof DOCK_ALONGS)[number];

export interface DockPosition {
  readonly edge: DockEdge;
  readonly along: DockAlong;
}

/** The value one radio item carries, and the only spelling of a slot. */
export type DockSlot = `${DockEdge}:${DockAlong}`;

export const slotValue = ({ edge, along }: DockPosition): DockSlot => `${edge}:${along}`;

/**
 * Every slot, by the value its radio item carries.
 *
 * **Twelve entries written out, and not twelve built by a loop.** A loop needs
 * an assertion to claim its result is total — `Object.fromEntries` answers
 * `Record<string, …>` — and ADR 0062 does not allow one. Written literally the
 * compiler checks each key against `DockSlot` and reports any that is missing,
 * so the table is total because it was proved total rather than because it was
 * generated by something that looked exhaustive.
 */
const DOCK_SLOTS = {
  'top:start': { edge: 'top', along: 'start' },
  'top:center': { edge: 'top', along: 'center' },
  'top:end': { edge: 'top', along: 'end' },
  'right:start': { edge: 'right', along: 'start' },
  'right:center': { edge: 'right', along: 'center' },
  'right:end': { edge: 'right', along: 'end' },
  'bottom:start': { edge: 'bottom', along: 'start' },
  'bottom:center': { edge: 'bottom', along: 'center' },
  'bottom:end': { edge: 'bottom', along: 'end' },
  'left:start': { edge: 'left', along: 'start' },
  'left:center': { edge: 'left', along: 'center' },
  'left:end': { edge: 'left', along: 'end' },
} as const satisfies Record<DockSlot, DockPosition>;

/**
 * The position a menu value names, or `null` for a string that names none.
 *
 * The parameter is `string` because that is what crosses the boundary: Base UI
 * types `MenuRadioGroup`'s `onValueChange` as `any`, so what comes back is
 * untrusted whatever was written on the way in. `null` is therefore honest
 * rather than defensive — and `dock-slots.test.ts` is what says the arm cannot
 * be reached from the menu, by holding every value the menu renders to a round
 * trip.
 *
 * **Two structures for one table, and each does a job the other cannot.** The
 * record above is checked against `DockSlot` and so proves the table total; the
 * `Map` below takes an arbitrary `string` and so needs no assertion to answer
 * for one. Indexing the record directly would want `value as DockSlot`, which
 * is a narrowing ADR 0062 does not admit — and it would be a lie besides, since
 * the whole point of the parameter is that the value may name
 * no slot at all.
 */
const SLOT_BY_VALUE: ReadonlyMap<string, DockPosition> = new Map(Object.entries(DOCK_SLOTS));

export const dockSlot = (value: string): DockPosition | null => SLOT_BY_VALUE.get(value) ?? null;

/**
 * The axis an edge puts the Dock on: left and right stack, top and bottom run.
 *
 * **Named, because the surface asks for it in three shapes.** Spelled inline
 * instead, `ALONG_LABEL`'s key and `orientationOf`'s return would have no
 * relation a compiler could check.
 */
export type DockOrientation = 'horizontal' | 'vertical';

/**
 * **A record, because a ternary answers for an edge it has never met.**
 *
 * Do not write it as `edge === 'left' || edge === 'right' ? 'vertical' :
 * 'horizontal'`. A fifth edge is a compile error at `EDGE_INSET`, `MENU_SIDE`,
 * `EDGE_LABEL`, `slotLabel` and `alongStyle` — every one a total record — and
 * the ternary would quietly call it horizontal, which is the one answer that
 * then decides how the Dock draws, which way its menus open and how its stops
 * are named.
 */
const ORIENTATION = {
  top: 'horizontal',
  bottom: 'horizontal',
  left: 'vertical',
  right: 'vertical',
} as const satisfies Record<DockEdge, DockOrientation>;

export const orientationOf = (edge: DockEdge): DockOrientation => ORIENTATION[edge];

/* --------------------------------------------------------------- geometry */

/**
 * A rectangle, in whatever coordinate space both sides of a comparison share.
 *
 * **`DOMRect` is what the caller measures and not what this asks for.** The
 * arithmetic below needs four numbers; asking for a `DOMRect` would put a DOM
 * in front of every test of it, for a type whose extra members — `x`, `y`,
 * `toJSON` — none of it reads. A `DOMRect` is structurally one of these, so the
 * measuring call sites are unchanged and the geometry becomes something a node
 * test can hand two rectangles to.
 */
export interface DockBox {
  readonly left: number;
  readonly top: number;
  readonly right: number;
  readonly bottom: number;
}

/**
 * The edge a release lands on: measured from the Dock's **own edges** rather
 * than from its centre.
 *
 * Do not measure from the centre: the Dock's width would vote. A horizontal
 * Dock ~600px wide has its centre ~300px from the left edge however far left
 * it is dragged, while its centre can be 40px from the top — so `top` would
 * win every time and no gesture would turn a top Dock into a left one near
 * that corner. The same asymmetry runs the other way for a vertical Dock near
 * the top edge.
 *
 * The gap to an edge does not know how big the Dock measuring it is, so both
 * corners are reachable from either direction and the orientation follows the
 * direction the reader dragged from. `dock-geometry.test.ts` holds it to that,
 * with a Dock wide enough for a centre rule to fail on.
 */
export const nearestEdge = (bounds: DockBox, box: DockBox): DockEdge => {
  const candidates = [
    { edge: 'top', distance: box.top - bounds.top },
    { edge: 'bottom', distance: bounds.bottom - box.bottom },
    { edge: 'left', distance: box.left - bounds.left },
    { edge: 'right', distance: bounds.right - box.right },
  ] as const satisfies readonly { edge: DockEdge; distance: number }[];
  return candidates.reduce((closest, candidate) =>
    candidate.distance < closest.distance ? candidate : closest,
  ).edge;
};

/**
 * The nearest of the three stops on `edge`, by the Dock's centre.
 *
 * **A stop is a place the Dock ends up, not a point on the edge**, and that is
 * the whole of the arithmetic. `start` puts a 600px-wide Dock's centre 300px
 * in, because the Dock has to fit; measuring that centre against the raw end of
 * the edge asks it to be somewhere it can never be, and lets the Dock's own
 * width vote: a Dock shoved hard into the left of a 1200px viewport has its
 * centre at 304, nearer the middle stop at 600 than a start stop at 0, and it
 * would snap back to the centre it had just been dragged out of.
 * `dock-geometry.test.ts` holds it to where each stop actually puts the Dock.
 *
 * **The inset is deliberately not part of it.** A stop's real position is
 * `inset + half` rather than `half`, but the three stops are hundreds of pixels
 * apart and the inset is 16, so it cannot change which is nearest — and leaving
 * it out keeps this function free of a placement policy that belongs to
 * `dockStyle`.
 */
export const nearestAlong = (bounds: DockBox, box: DockBox, edge: DockEdge): DockAlong => {
  const horizontal = orientationOf(edge) === 'horizontal';
  const position = horizontal
    ? (box.left + box.right) / 2 - bounds.left
    : (box.top + box.bottom) / 2 - bounds.top;
  const extent = horizontal ? bounds.right - bounds.left : bounds.bottom - bounds.top;
  // Half the Dock's own size along the edge it is on: how far its centre must
  // stand off either end for the Dock to fit inside the container at all.
  const half = (horizontal ? box.right - box.left : box.bottom - box.top) / 2;
  const stops = [
    { along: 'start', at: half },
    { along: 'center', at: extent / 2 },
    { along: 'end', at: extent - half },
  ] as const satisfies readonly { along: DockAlong; at: number }[];
  return stops.reduce((closest, stop) =>
    Math.abs(position - stop.at) < Math.abs(position - closest.at) ? stop : closest,
  ).along;
};

/**
 * The slot a release lands in: an edge, then a stop along it.
 *
 * Two independent questions rather than one list of eight, because the edge is
 * what decides the dock's orientation and which way its menus open, and the
 * stop only decides where along that edge it sits. Asking them separately is
 * also what makes a corner reachable from either side with a different
 * orientation, which a flat list of eight positions could not express.
 */
export const nearestSlot = (bounds: DockBox, box: DockBox): DockPosition => {
  const edge = nearestEdge(bounds, box);
  return { edge, along: nearestAlong(bounds, box, edge) };
};

/* ---------------------------------------------------------------- placing */

/**
 * Which way a menu opens, decided by the dock rather than the control.
 *
 * A bottom-edge dock's menus must open upward: Base UI's default `bottom`
 * puts the popup below the viewport, where it is open and invisible, which
 * reads exactly like a control that does nothing.
 */
export type MenuSide = 'top' | 'bottom' | 'left' | 'right';

/** A menu opens into the canvas, never off the edge the dock is against. */
export const MENU_SIDE = {
  top: 'bottom',
  bottom: 'top',
  left: 'right',
  right: 'left',
} as const satisfies Record<DockEdge, MenuSide>;

/**
 * How far each edge holds the dock off.
 *
 * The bottom is not the same as the others and this asymmetry is the point:
 * the macOS Dock, its reveal strip and the window resize handle all live in the
 * last few dozen pixels, and the OS takes the pointer before the page does.
 */
const EDGE_INSET = {
  top: 16,
  right: 16,
  bottom: 44,
  left: 16,
} satisfies Record<DockEdge, number>;

/**
 * The inline position a docked Dock (or its snap hint) is drawn at.
 *
 * Structurally a subset of React's `CSSProperties`, so a caller passes it to
 * `style` unchanged while this module stays free of React.
 */
export interface DockPlacementStyle {
  readonly top?: number | string;
  readonly right?: number | string;
  readonly bottom?: number | string;
  readonly left?: number | string;
  readonly transform?: string;
}

/**
 * The two insets a docked position spends: one holding it off its own edge, one
 * holding it off the edge it is aligned to at a corner.
 *
 * `center` is the only stop that translates, because it is the only one
 * positioned by its own midpoint. `start` and `end` are pinned to a corner, and
 * a translate there would hang the dock half off the container.
 */
const alongStyle = (edge: DockEdge, along: DockAlong): DockPlacementStyle => {
  const cross = EDGE_INSET[edge === 'bottom' ? 'top' : edge === 'right' ? 'left' : edge];
  if (orientationOf(edge) === 'horizontal') {
    if (along === 'start') return { left: cross };
    if (along === 'end') return { right: cross };
    return { left: '50%', transform: 'translateX(-50%)' };
  }
  if (along === 'start') return { top: cross };
  if (along === 'end') return { bottom: EDGE_INSET.bottom };
  return { top: '50%', transform: 'translateY(-50%)' };
};

export const dockStyle = ({ edge, along }: DockPosition): DockPlacementStyle => {
  const inset = EDGE_INSET[edge];
  const anchor =
    edge === 'top'
      ? { top: inset }
      : edge === 'bottom'
        ? { bottom: inset }
        : edge === 'left'
          ? { left: inset }
          : { right: inset };
  return { ...anchor, ...alongStyle(edge, along) };
};

/* ----------------------------------------------------------------- naming */

/**
 * The twelve slots, as something other than a drag can offer them.
 *
 * **A drag cannot be the only way to move the Dock**, on two independent
 * grounds that happen to have one answer. It is not reachable from a keyboard
 * at all, and it is not reachable from a test either: a synthetic pointer
 * sequence carries no pointer capture, and stubbing capture to force one
 * freezes the renderer, which is the whole reason `DockedLeft` exists as a
 * second story rather than as an assertion inside the first.
 *
 * So the grip discloses the set, and the drag becomes the shortcut rather than
 * the mechanism. That is the ordinary reading of a grip on a movable panel, and
 * it costs nothing the drag was providing.
 *
 * **Twelve rows in four labelled groups, and not eight.** The eight *targets* —
 * four corners and four edge-middles — are what the geometry offers a pointer,
 * because a corner is one place two edges both reach. A menu is not a place,
 * and a reader choosing from it is making the two choices the drag makes
 * separately: the edge, which decides the orientation, and the stop along it.
 * Collapsing them to eight would make the two corners that carry an orientation
 * choice indistinguishable from the two that do not.
 */
export const EDGE_LABEL = {
  top: 'Top edge',
  right: 'Right edge',
  bottom: 'Bottom edge',
  left: 'Left edge',
} as const satisfies Record<DockEdge, string>;

/**
 * A stop is named for the direction its edge runs, not for the enum.
 *
 * `start` of the top edge is the left of the screen and `start` of the left
 * edge is the top of it, and a reader picking a slot is picking a place rather
 * than a coordinate. One name for both would have to be the enum's, which names
 * neither.
 */
const ALONG_LABEL = {
  horizontal: { start: 'Left', center: 'Centre', end: 'Right' },
  vertical: { start: 'Top', center: 'Middle', end: 'Bottom' },
} as const satisfies Record<DockOrientation, Record<DockAlong, string>>;

export const alongLabel = (edge: DockEdge, along: DockAlong): string =>
  ALONG_LABEL[orientationOf(edge)][along];

/** Where the Dock is, said the way the grip's label says it. */
export const slotLabel = (position: DockPosition): string =>
  `${EDGE_LABEL[position.edge]}, ${alongLabel(position.edge, position.along).toLowerCase()}`;

/* --------------------------------------------------------------- dragging */

/**
 * How far a press travels before it stops being a click.
 *
 * Without it every press on the grip is a drag of zero pixels, and a reader who
 * clicks the grip with an unsteady hand redocks the surface instead of opening
 * the slots. Four pixels is what a browser's own click tolerance is worth.
 */
const DRAG_THRESHOLD = 4;

/** A pointer position, in client coordinates. */
export interface PointerPoint {
  readonly x: number;
  readonly y: number;
}

/** Whether a press that began at `from` and is now at `to` has become a drag. */
export const exceedsDragThreshold = (from: PointerPoint, to: PointerPoint): boolean =>
  Math.abs(to.x - from.x) > DRAG_THRESHOLD || Math.abs(to.y - from.y) > DRAG_THRESHOLD;
