export interface KeyBinding {
  readonly module: `packages/${'app' | 'ui'}/src/${string}`;
  readonly sourceKey: string;
  readonly occurrence: number;
  readonly key: string;
  readonly surface: string;
  readonly behaviour: string;
}

/** Every keyboard binding authored by Hyper in the app and UI packages. */
export const KEY_BINDINGS: readonly KeyBinding[] = [
  {
    module: 'packages/ui/src/MarkdownSourceEditor.tsx',
    sourceKey: 'Escape',
    occurrence: 1,
    key: 'Escape',
    surface: 'Markdown source editor',
    behaviour: 'withhold the Resource surface cancel key from CodeMirror',
  },
  {
    module: 'packages/ui/src/MarkdownSourceEditor.tsx',
    sourceKey: 'Mod-Enter',
    occurrence: 1,
    key: 'Mod-Enter',
    surface: 'Markdown source editor',
    behaviour: 'withhold the Resource surface commit chord from CodeMirror',
  },
  {
    module: 'packages/ui/src/MarkdownResourceBody.tsx',
    sourceKey: 'Escape',
    occurrence: 1,
    key: 'Escape',
    surface: 'Markdown Resource body',
    behaviour: 'cancel Markdown editing',
  },
  {
    module: 'packages/ui/src/MarkdownResourceBody.tsx',
    sourceKey: 'Enter',
    occurrence: 1,
    key: 'Mod-Enter',
    surface: 'Markdown Resource body',
    behaviour: 'commit Markdown editing',
  },
  {
    module: 'packages/ui/src/InlineTitleEditor.tsx',
    sourceKey: 'Enter',
    occurrence: 1,
    key: 'Enter',
    surface: 'Inline title editor',
    behaviour: 'complete the title edit',
  },
  {
    module: 'packages/ui/src/InlineTitleEditor.tsx',
    sourceKey: 'Escape',
    occurrence: 1,
    key: 'Escape',
    surface: 'Inline title editor',
    behaviour: 'cancel the title edit and restore surface focus',
  },
  {
    module: 'packages/app/src/components/SpaceCanvas.tsx',
    sourceKey: 'Enter',
    occurrence: 1,
    key: 'Enter',
    surface: 'Canvas Resource',
    behaviour: 'open the focused Resource',
  },
  {
    module: 'packages/app/src/components/SpaceCanvas.tsx',
    sourceKey: ' ',
    occurrence: 1,
    key: 'Space',
    surface: 'Canvas Resource',
    behaviour: 'open the focused Resource',
  },
  {
    module: 'packages/app/src/components/SpaceCanvas.tsx',
    sourceKey: 'C',
    occurrence: 1,
    key: 'C',
    surface: 'Canvas',
    behaviour: 'add a Resource on an unmodified, non-repeating press',
  },
  {
    module: 'packages/app/src/components/SpaceCanvas.tsx',
    sourceKey: 'F2',
    occurrence: 1,
    key: 'F2',
    surface: 'Canvas',
    behaviour: 'begin renaming the selected Resource',
  },
  {
    module: 'packages/app/src/presenting-keys.ts',
    sourceKey: ' ',
    occurrence: 1,
    key: 'Space',
    surface: 'Focused control while presenting',
    behaviour: 'defer to native control activation',
  },
  {
    module: 'packages/app/src/presenting-keys.ts',
    sourceKey: 'Enter',
    occurrence: 1,
    key: 'Enter',
    surface: 'Focused control while presenting',
    behaviour: 'defer to native control activation',
  },
  {
    module: 'packages/app/src/presenting-keys.ts',
    sourceKey: 'ArrowRight',
    occurrence: 1,
    key: 'ArrowRight',
    surface: 'Presenting',
    behaviour: 'advance along the selected outgoing Edge',
  },
  {
    module: 'packages/app/src/presenting-keys.ts',
    sourceKey: ' ',
    occurrence: 2,
    key: 'Space',
    surface: 'Presenting',
    behaviour: 'advance along the selected outgoing Edge',
  },
  {
    module: 'packages/app/src/presenting-keys.ts',
    sourceKey: 'ArrowLeft',
    occurrence: 1,
    key: 'ArrowLeft',
    surface: 'Presenting',
    behaviour: 'retreat through Traversal history',
  },
  {
    module: 'packages/app/src/presenting-keys.ts',
    sourceKey: 'ArrowUp',
    occurrence: 1,
    key: 'ArrowUp',
    surface: 'Presenting',
    behaviour: 'select the previous outgoing Edge',
  },
  {
    module: 'packages/app/src/presenting-keys.ts',
    sourceKey: 'ArrowDown',
    occurrence: 1,
    key: 'ArrowDown',
    surface: 'Presenting',
    behaviour: 'select the next outgoing Edge',
  },
  {
    module: 'packages/app/src/presenting-keys.ts',
    sourceKey: 'Escape',
    occurrence: 1,
    key: 'Escape',
    surface: 'Presenting',
    behaviour: 'leave presentation',
  },
  {
    module: 'packages/app/src/components/SpaceCanvas.tsx',
    sourceKey: 'Backspace',
    occurrence: 1,
    key: 'Backspace',
    surface: 'Canvas',
    behaviour:
      'remove the focused Resource, else the selected Resource or Edge, through Space Authoring, on an unmodified, non-repeating press',
  },
  {
    module: 'packages/app/src/components/SpaceCanvas.tsx',
    sourceKey: 'Delete',
    occurrence: 1,
    key: 'Delete',
    surface: 'Canvas',
    behaviour:
      'remove the focused Resource, else the selected Resource or Edge, through Space Authoring, on an unmodified, non-repeating press',
  },
  {
    module: 'packages/app/src/edge-authoring-react.tsx',
    sourceKey: 'Alt',
    occurrence: 1,
    key: 'Alt',
    surface: 'Edge authoring',
    behaviour: 'modify an empty drop into a new Resource connection',
  },
  {
    module: 'packages/app/src/edge-authoring-react.tsx',
    sourceKey: 'Enter',
    occurrence: 1,
    key: 'Enter',
    surface: 'Edge',
    behaviour: "move focus from the focused Active Graph Edge into its toolbar's first command",
  },
  {
    module: 'packages/app/src/components/AuthorableEdge.tsx',
    sourceKey: 'Escape',
    occurrence: 1,
    key: 'Escape',
    surface: 'Edge toolbar and Title',
    behaviour: 'return focus from the Edge chrome to the Edge',
  },
];
