// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as SqliteTypes } from '@prisma-next/adapter-sqlite/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:500b8c46f9e1b6fc97b6575af513184ac010b76b622c3bcbebf6065b151b26a1'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:3a90adf23ead13df33159d39784aebaca85997a7e11b6b92346615986381dcf3'>;
export type ProfileHash =
  ProfileHashBase<'sha256:3cc333ecad9f3f4c7229370a9d2c37e908cdce0f8d2e9fb132d50605b024eff2'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly RepositoryState: {
      readonly singletonId: CodecTypes['sqlite/integer@1']['output'];
      readonly metaSpaceId: CodecTypes['sqlite/text@1']['output'];
    };
    readonly Space: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly document: CodecTypes['sqlite/json@1']['output'];
      readonly revision: CodecTypes['sqlite/text@1']['output'];
      readonly exportedRevision: CodecTypes['sqlite/text@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Thing: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly spaceId: CodecTypes['sqlite/text@1']['output'];
      readonly document: CodecTypes['sqlite/json@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly RepositoryState: {
      readonly singletonId: CodecTypes['sqlite/integer@1']['input'];
      readonly metaSpaceId: CodecTypes['sqlite/text@1']['input'];
    };
    readonly Space: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly document: CodecTypes['sqlite/json@1']['input'];
      readonly revision: CodecTypes['sqlite/text@1']['input'];
      readonly exportedRevision: CodecTypes['sqlite/text@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Thing: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly spaceId: CodecTypes['sqlite/text@1']['input'];
      readonly document: CodecTypes['sqlite/json@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly repository_state: {
      readonly meta_space_id: CodecTypes['sqlite/text@1']['output'];
      readonly singleton_id: CodecTypes['sqlite/integer@1']['output'];
    };
    readonly spaces: {
      readonly created_at: CodecTypes['sqlite/datetime@1']['output'];
      readonly document: CodecTypes['sqlite/json@1']['output'];
      readonly exported_revision: CodecTypes['sqlite/text@1']['output'] | null;
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly revision: CodecTypes['sqlite/text@1']['output'];
      readonly updated_at: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly things: {
      readonly created_at: CodecTypes['sqlite/datetime@1']['output'];
      readonly document: CodecTypes['sqlite/json@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly space_id: CodecTypes['sqlite/text@1']['output'];
      readonly updated_at: CodecTypes['sqlite/datetime@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly repository_state: {
      readonly meta_space_id: CodecTypes['sqlite/text@1']['input'];
      readonly singleton_id: CodecTypes['sqlite/integer@1']['input'];
    };
    readonly spaces: {
      readonly created_at: CodecTypes['sqlite/datetime@1']['input'];
      readonly document: CodecTypes['sqlite/json@1']['input'];
      readonly exported_revision: CodecTypes['sqlite/text@1']['input'] | null;
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly revision: CodecTypes['sqlite/text@1']['input'];
      readonly updated_at: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly things: {
      readonly created_at: CodecTypes['sqlite/datetime@1']['input'];
      readonly document: CodecTypes['sqlite/json@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly space_id: CodecTypes['sqlite/text@1']['input'];
      readonly updated_at: CodecTypes['sqlite/datetime@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly repository_state: {
              columns: {
                readonly singleton_id: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/integer@1', 1>;
                  };
                };
                readonly meta_space_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['singleton_id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly columns: readonly ['meta_space_id'];
                  readonly name: 'repository_state_meta_space_id_idx';
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'repository_state';
                    readonly columns: readonly ['meta_space_id'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'spaces';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly spaces: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly document: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/json@1';
                  readonly nullable: false;
                };
                readonly revision: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', '0'>;
                  };
                };
                readonly exported_revision: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly things: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly space_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly document: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/json@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [{ readonly columns: readonly ['space_id'] }];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'things';
                    readonly columns: readonly ['space_id'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'spaces';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly spaces: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Space' };
    readonly repository_state: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'RepositoryState';
    };
    readonly things: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Thing' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly RepositoryState: {
            readonly fields: {
              readonly singletonId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly metaSpaceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: {
              readonly metaSpace: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Space';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['metaSpaceId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'repository_state';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly singletonId: { readonly column: 'singleton_id' };
                readonly metaSpaceId: { readonly column: 'meta_space_id' };
              };
            };
          };
          readonly Space: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly document: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/json@1' };
              };
              readonly revision: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly exportedRevision: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly repositoryStates: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'RepositoryState';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['metaSpaceId'];
                };
              };
              readonly things: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Thing';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['spaceId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'spaces';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly document: { readonly column: 'document' };
                readonly revision: { readonly column: 'revision' };
                readonly exportedRevision: { readonly column: 'exported_revision' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Thing: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly spaceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly document: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/json@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly space: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Space';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['spaceId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'things';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly spaceId: { readonly column: 'space_id' };
                readonly document: { readonly column: 'document' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly enums: false;
      readonly foreignKeys: true;
      readonly jsonAgg: true;
      readonly lateral: false;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: '__unbound__';
            readonly table: 'spaces';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: '__unbound__';
            readonly table: 'things';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
