// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:d37fa0a38782869fa17be8d7b6e3e58f932b2445f56f9f13155793e22084e74e'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:f9be1da4ef42827ebd2b1d6e35e7e84be1f6d78783f54d1796a2b34881777b70'>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Card: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly spaceId: CodecTypes['pg/uuid@1']['output'];
      readonly document: CodecTypes['pg/jsonb@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly RepositoryState: {
      readonly singletonId: CodecTypes['pg/int4@1']['output'];
      readonly metaSpaceId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Space: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly document: CodecTypes['pg/jsonb@1']['output'];
      readonly revision: CodecTypes['pg/int8@1']['output'];
      readonly exportedRevision: CodecTypes['pg/int8@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly entry: CodecTypes['pg/bool@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Card: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly spaceId: CodecTypes['pg/uuid@1']['input'];
      readonly document: CodecTypes['pg/jsonb@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly RepositoryState: {
      readonly singletonId: CodecTypes['pg/int4@1']['input'];
      readonly metaSpaceId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Space: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly document: CodecTypes['pg/jsonb@1']['input'];
      readonly revision: CodecTypes['pg/int8@1']['input'];
      readonly exportedRevision: CodecTypes['pg/int8@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly entry: CodecTypes['pg/bool@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly cards: {
      readonly created_at: CodecTypes['pg/timestamptz@1']['output'];
      readonly document: CodecTypes['pg/jsonb@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly space_id: CodecTypes['pg/uuid@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly repository_state: {
      readonly meta_space_id: CodecTypes['pg/uuid@1']['output'];
      readonly singleton_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly spaces: {
      readonly created_at: CodecTypes['pg/timestamptz@1']['output'];
      readonly document: CodecTypes['pg/jsonb@1']['output'];
      readonly entry: CodecTypes['pg/bool@1']['output'] | null;
      readonly exported_revision: CodecTypes['pg/int8@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly revision: CodecTypes['pg/int8@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly cards: {
      readonly created_at: CodecTypes['pg/timestamptz@1']['input'];
      readonly document: CodecTypes['pg/jsonb@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly space_id: CodecTypes['pg/uuid@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly repository_state: {
      readonly meta_space_id: CodecTypes['pg/uuid@1']['input'];
      readonly singleton_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly spaces: {
      readonly created_at: CodecTypes['pg/timestamptz@1']['input'];
      readonly document: CodecTypes['pg/jsonb@1']['input'];
      readonly entry: CodecTypes['pg/bool@1']['input'] | null;
      readonly exported_revision: CodecTypes['pg/int8@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly revision: CodecTypes['pg/int8@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly cards: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                  readonly typeRef: 'Uuid';
                };
                readonly space_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly document: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [{ readonly columns: readonly ['space_id'] }];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'cards';
                    readonly columns: readonly ['space_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'spaces';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly repository_state: {
              columns: {
                readonly singleton_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly meta_space_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
              };
              primaryKey: { readonly columns: readonly ['singleton_id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly spaces: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                  readonly typeRef: 'Uuid';
                };
                readonly document: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly revision: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int8@1', 0>;
                  };
                };
                readonly exported_revision: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
                readonly entry: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['entry'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly types: {
      readonly Uuid: {
        readonly kind: 'codec-instance';
        readonly codecId: 'pg/uuid@1';
        readonly nativeType: 'uuid';
        readonly typeParams: Record<string, never>;
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly spaces: { readonly namespace: 'public' & NamespaceId; readonly model: 'Space' };
    readonly repository_state: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RepositoryState';
    };
    readonly cards: { readonly namespace: 'public' & NamespaceId; readonly model: 'Card' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Card: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly spaceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly document: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: {
              readonly space: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Space';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['spaceId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'cards';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly spaceId: { readonly column: 'space_id' };
                readonly document: { readonly column: 'document' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly RepositoryState: {
            readonly fields: {
              readonly singletonId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly metaSpaceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'repository_state';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly singletonId: { readonly column: 'singleton_id' };
                readonly metaSpaceId: { readonly column: 'meta_space_id' };
              };
            };
          };
          readonly Space: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly document: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly revision: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly exportedRevision: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly entry: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly cards: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Card' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['spaceId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'spaces';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly document: { readonly column: 'document' };
                readonly revision: { readonly column: 'revision' };
                readonly exportedRevision: { readonly column: 'exported_revision' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly entry: { readonly column: 'entry' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'cards';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'spaces';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
